// ============================================================================
// TERMS AND CONDITIONS SCREEN - NutriSnap
// ============================================================================
import React from "react";
import { View, ScrollView, StyleSheet, TouchableOpacity } from "react-native";
import { Text } from "react-native-paper";

export default function TermsScreen({ themeColors, onBack }) {
    const Section = ({ title, children }) => (
        <View style={styles.section}>
            <Text style={[styles.sectionTitle, { color: themeColors.text }]}>{title}</Text>
            <Text style={[styles.sectionBody, { color: themeColors.subText }]}>{children}</Text>
        </View>
    );

    return (
        <View style={{ flex: 1 }}>
            <ScrollView style={{ flex: 1 }} contentContainerStyle={styles.scrollContent}>
                {/* Header */}
                <View style={styles.header}>
                    <TouchableOpacity onPress={onBack} style={styles.backButton}>
                        <Text style={[styles.backText, { color: themeColors.primary, fontSize: 22 }]}>←</Text>
                    </TouchableOpacity>
                    <Text style={[styles.headerTitle, { color: themeColors.text }]}>Terms & Conditions</Text>
                    <View style={{ width: 50 }} />
                </View>

                <View style={[styles.card, { backgroundColor: themeColors.card }]}>
                    <Text style={[styles.lastUpdated, { color: themeColors.subText }]}>Last Updated: February 7, 2026</Text>

                    <Section title="1. Acceptance of Terms">
                        {`Welcome to NutriSnap. These Terms and Conditions ("Terms") govern your access to and use of the NutriSnap mobile application ("App"), operated by NutriSnap ("we," "our," or "us").

By creating an account and using the App, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you must not use the App.

We reserve the right to modify these Terms at any time. If we make material changes, we will provide notice through the App. Your continued use of the App after such notification constitutes acceptance of the modified Terms.`}
                    </Section>

                    <Section title="2. Eligibility">
                        {`To use NutriSnap, you must:

- Be at least 13 years of age (or the minimum age required in your jurisdiction)
- Have the legal capacity to enter into a binding agreement
- Not be prohibited from using the App under applicable laws

If you are under 18, you must have permission from a parent or legal guardian to use the App. By using NutriSnap, you represent and warrant that you meet these eligibility requirements.`}
                    </Section>

                    <Section title="3. Account Registration">
                        {`To access NutriSnap's features, you must create an account by providing:

- A valid email address
- A secure password (minimum 6 characters)
- Your display name (optional but recommended)

You are responsible for:
- Maintaining the confidentiality of your account credentials
- All activities that occur under your account
- Notifying us immediately of any unauthorized access or use of your account

We reserve the right to suspend or terminate accounts that violate these Terms or that we reasonably believe are being used fraudulently.`}
                    </Section>

                    <Section title="4. Description of Services">
                        {`NutriSnap provides the following services:

a) AI-Powered Food Analysis: Using Google's Gemini AI, the App analyzes photos of food to estimate nutritional content including calories, macronutrients (protein, carbohydrates, fat), and other nutritional values.

b) Meal Tracking: Log and track your daily meals, view nutritional summaries, and monitor your eating habits over time.

c) Health Scoring: Daily health scores based on your nutritional intake, goal adherence, and consistency.

d) Analytics & Reports: Visualize your nutrition data through charts, trends, and personalized insights.

e) Goal Planning: Set fitness goals, track weight, and receive personalized calorie and macronutrient recommendations.

f) Smart Reminders: Optional notifications to help you maintain consistent meal logging habits.

g) Streak Tracking: Monitor your daily logging consistency with streaks and badges.`}
                    </Section>

                    <Section title="5. Important Health Disclaimer">
                        {`NUTRISNAP IS NOT A MEDICAL DEVICE AND IS NOT INTENDED TO DIAGNOSE, TREAT, CURE, OR PREVENT ANY DISEASE OR HEALTH CONDITION.

The nutritional information provided by the App is generated by artificial intelligence and is an estimate only. The accuracy of nutritional data depends on many factors including food identification, portion size estimation, and preparation methods.

You should:
- Not rely solely on NutriSnap for dietary or medical decisions
- Consult with a qualified healthcare professional or registered dietitian before making significant changes to your diet
- Seek immediate medical attention if you have concerns about your health
- Not use the App as a substitute for professional medical advice, diagnosis, or treatment

The calorie targets, macronutrient recommendations, and goal planning features are based on general nutritional guidelines and mathematical formulas (such as the Mifflin-St Jeor equation). Individual needs may vary significantly based on medical conditions, medications, and other factors.

WE EXPRESSLY DISCLAIM ANY LIABILITY FOR ANY HEALTH CONSEQUENCES ARISING FROM YOUR USE OF NUTRISNAP OR YOUR RELIANCE ON INFORMATION PROVIDED THROUGH THE APP.`}
                    </Section>

                    <Section title="6. User Content">
                        {`When you use NutriSnap, you may submit content including:
- Food photos
- Meal descriptions
- Weight and body metric data
- Goal and preference settings

You retain ownership of your content. By submitting content to the App, you grant us a non-exclusive, worldwide, royalty-free license to use, store, process, and display your content solely for the purpose of providing and improving the App's services.

You agree not to submit content that:
- Is illegal, harmful, threatening, or abusive
- Infringes on any third party's intellectual property rights
- Contains malware, viruses, or harmful code
- Violates any applicable laws or regulations`}
                    </Section>

                    <Section title="7. Acceptable Use">
                        {`You agree to use NutriSnap only for its intended purpose of personal nutrition tracking. You must not:

- Attempt to reverse engineer, decompile, or disassemble the App
- Use the App for any commercial purpose without our written consent
- Attempt to gain unauthorized access to our systems or other users' accounts
- Interfere with or disrupt the App's servers or networks
- Use automated systems or bots to access the App
- Scrape, data-mine, or extract data from the App
- Use the App to transmit any unauthorized advertising or promotional materials
- Impersonate another person or entity
- Use the App in any way that violates applicable laws or regulations`}
                    </Section>

                    <Section title="8. Intellectual Property">
                        {`The App, including its design, features, code, content, graphics, and user interface, is owned by NutriSnap and is protected by copyright, trademark, and other intellectual property laws.

The NutriSnap name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of NutriSnap. You must not use such marks without our prior written permission.

Open-source components used in the App are subject to their respective licenses.`}
                    </Section>

                    <Section title="9. Third-Party Services">
                        {`NutriSnap integrates with the following third-party services:

a) Google Firebase: For authentication, data storage, and file storage. Your use of these services is subject to Google's Terms of Service.

b) Google Gemini AI: For food photo analysis. Your use is subject to Google's AI Terms of Service.

c) Expo: For app delivery and updates. Subject to Expo's terms of service.

We are not responsible for the practices or content of third-party services. We encourage you to review the terms and privacy policies of any third-party services that the App integrates with.`}
                    </Section>

                    <Section title="10. Subscription and Fees">
                        {`NutriSnap is currently offered as a free application. We reserve the right to introduce paid features or subscription plans in the future.

If we introduce paid features:
- We will clearly communicate pricing before any charges
- You will have the option to continue using free features
- Subscriptions will be managed through the Apple App Store or Google Play Store
- Refund policies of the respective app stores will apply`}
                    </Section>

                    <Section title="11. Limitation of Liability">
                        {`TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

a) THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.

b) WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.

c) WE DO NOT WARRANT THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY NUTRITIONAL INFORMATION PROVIDED BY THE APP.

d) IN NO EVENT SHALL NUTRISNAP, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.

e) OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM, OR $100, WHICHEVER IS GREATER.`}
                    </Section>

                    <Section title="12. Indemnification">
                        {`You agree to defend, indemnify, and hold harmless NutriSnap and its officers, directors, employees, contractors, agents, licensors, and suppliers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to:

- Your violation of these Terms
- Your use of the App
- Your violation of any third-party rights
- Any content you submit through the App`}
                    </Section>

                    <Section title="13. Termination">
                        {`We may terminate or suspend your account and access to the App immediately, without prior notice or liability, for any reason, including if you breach these Terms.

Upon termination:
- Your right to use the App will cease immediately
- We may delete your account data in accordance with our Privacy Policy
- Provisions of these Terms that by their nature should survive termination shall survive (including ownership, warranty disclaimers, indemnity, and limitations of liability)

You may terminate your account at any time by contacting us or deleting your account through the App's settings.`}
                    </Section>

                    <Section title="14. Dispute Resolution">
                        {`a) Governing Law: These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which NutriSnap operates, without regard to its conflict of law provisions.

b) Informal Resolution: Before filing any formal dispute, you agree to first contact us and attempt to resolve the dispute informally for at least 30 days.

c) Arbitration: Any disputes that cannot be resolved informally shall be resolved through binding arbitration in accordance with the rules of the applicable arbitration body in the jurisdiction.

d) Class Action Waiver: You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.

e) Exceptions: Nothing in this section shall prevent either party from seeking injunctive or equitable relief in court for matters relating to intellectual property rights or unauthorized access to the App.`}
                    </Section>

                    <Section title="15. Severability">
                        {`If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other provision of these Terms, and these Terms shall be construed as if such invalid, illegal, or unenforceable provision had never been contained herein.`}
                    </Section>

                    <Section title="16. Entire Agreement">
                        {`These Terms, together with the Privacy Policy, constitute the entire agreement between you and NutriSnap regarding the use of the App, and supersede and replace any prior agreements we might have had between us regarding the App.`}
                    </Section>

                    <Section title="17. Contact Information">
                        {`If you have any questions about these Terms, please contact us at:

Email: navyvibrance@gmail.com`}
                    </Section>
                </View>

                <View style={{ height: 32 }} />
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    scrollContent: { padding: 16, paddingBottom: 32 },
    header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
    backButton: { padding: 4 },
    backText: { fontSize: 16, fontWeight: "600" },
    headerTitle: { fontSize: 22, fontWeight: "bold" },
    card: { borderRadius: 16, padding: 16 },
    lastUpdated: { fontSize: 12, marginBottom: 16, fontStyle: "italic" },
    section: { marginBottom: 24 },
    sectionTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 8 },
    sectionBody: { fontSize: 13, lineHeight: 20 },
});
