// ============================================================================
// TERMS AND CONDITIONS SCREEN - NutriSnap (Simplified)
// ============================================================================
import React from "react";
import { View, ScrollView, StyleSheet, TouchableOpacity } from "react-native";
import { Text } from "react-native-paper";

export default function TermsScreen({ themeColors, onBack }) {
    const Section = ({ title, children }) => (
        <View style={styles.section}>
            <Text style={[styles.sectionTitle, { color: themeColors.text }]}>{title}</Text>
            <Text style={[styles.sectionBody, { color: themeColors.subText }]}>{children}</Text>
        </View>
    );

    return (
        <View style={{ flex: 1 }}>
            <ScrollView style={{ flex: 1 }} contentContainerStyle={styles.scrollContent}>
                <View style={styles.header}>
                    <TouchableOpacity onPress={onBack} style={styles.backButton}>
                        <Text style={[styles.backText, { color: themeColors.primary, fontSize: 22 }]}>←</Text>
                    </TouchableOpacity>
                    <Text style={[styles.headerTitle, { color: themeColors.text }]}>Terms & Conditions</Text>
                    <View style={{ width: 50 }} />
                </View>

                <View style={[styles.card, { backgroundColor: themeColors.card }]}>
                    <Text style={[styles.lastUpdated, { color: themeColors.subText }]}>Last Updated: February 13, 2026</Text>

                    <Section title="1. Acceptance">
                        By using NutriSnap, you agree to these Terms. If you don't agree, please do not use the app.
                    </Section>

                    <Section title="2. Description of Service">
                        NutriSnap provides AI-powered meal analysis using Google Gemini and simple nutrition tracking tools to help you monitor your health goals.
                    </Section>

                    <Section title="3. HEALTH & MEDICAL DISCLAIMER">
                        {`NUTRISNAP IS NOT A MEDICAL DEVICE. All nutritional data, calorie counts, and macronutrient estimates are generated by AI and should be treated as estimations only.

- Seek professional medical advice before making significant dietary changes.
- Do not use this app to diagnose or treat any medical condition.
- We are not responsible for any health consequences resulting from your use of the app.`}
                    </Section>

                    <Section title="4. User Accounts">
                        You are responsible for keeping your account secure. We reserve the right to suspend accounts that violate our terms or misuse the service.
                    </Section>

                    <Section title="5. Prohibited Use">
                        You agree not to misuse the app, attempt to reverse engineer its code, or use it for any illegal purposes.
                    </Section>

                    <Section title="6. Liability & Disclaimers">
                        NutriSnap is provided "As-Is" and "As-Available". We do not guarantee 100% accuracy of nutritional data. Our liability is limited to the maximum extent permitted by law.
                    </Section>

                    <Section title="7. Contact Us">
                        Questions? Email us at: navygeeks@gmail.com
                    </Section>
                </View>

                <View style={{ height: 32 }} />
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    scrollContent: { padding: 16, paddingBottom: 32 },
    header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
    backButton: { padding: 4 },
    backText: { fontSize: 16, fontWeight: "600" },
    headerTitle: { fontSize: 22, fontWeight: "bold" },
    card: { borderRadius: 16, padding: 16 },
    lastUpdated: { fontSize: 12, marginBottom: 16, fontStyle: "italic" },
    section: { marginBottom: 24 },
    sectionTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 8 },
    sectionBody: { fontSize: 13, lineHeight: 20 },
});
